### ISSUE TITLE
[BUG]  VCS information for the components are missing 

### ISSUE THREAD

**Issue by FarooqAftab** [CycloneDX/cyclonedx-python#785]
## Describe the bug

While generating the SBOM file, vcs information are missing .
Used below command to generated SBOM

`cyclonedx-py requirements -i requirements.txt --pyproject "/home/python_sbom_ex/hello-world-python/pyproject.toml"  --outfile cycloneNew.xml --schema-version 1.4 --output-format XML`

## To Reproduce

Steps to reproduce the behavior

## Screenshots or output-paste

If applicable, add screenshots or past the output to help explain your problem.

## Environment

- _cyclonedx-py_ version: 
- Python version: 
- OS:

**Comment by jkowalleck** [comment]
@FarooqAftab where in the SBOM is the information missing, for the metadata component or any of the depending components?
Could you upload the `requirements.txt` file and `pyproject.toml` file used? 
Could you upload the resulting `cycloneNew.xml` file?

**Comment by FarooqAftab** [comment]
Hi @jkowalleck 
Please find the attached files for your reference.
The vcs value is missing in the metadata and also in the components.

[files.zip](https://github.com/user-attachments/files/16942527/files.zip)

**Comment by jkowalleck** [comment]
> Hi @jkowalleck Please find the attached files for your reference. The vcs value is missing in the metadata and also in the components.
> 
> [files.zip](https://github.com/user-attachments/files/16942527/files.zip)

the provided `requirements.txt` does not hold any information for VCS related information:
```text
grequests==2.26.0
flask==2.0.1
```

the provided `pyproject.toml`  does not hold any information for VCS related information:
```toml
[project]
name = "hello-world-python"
version = "0.0.1"
authors = [
  { name="Example Author", email="author@example.com" },
]
description = "A simple Flask application"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"
```

the non-providedVCS information was not carried over to SBOM.
Conclusion: all worls as expected.
